### ISSUE TITLE
[Bug]: Report failed to Render

### ISSUE THREAD

**Issue by lkacimi** [nightwatchjs/html-reporter#23] opened 2023-02-17 10:02 UTC
[Enter feedback here]
    
  ---

  **Error Details**
  ```javascript
  kA@file:///Volumes/Workplace/estore/tests_output/nightwatch-html-report/index.html:119:14506
TA@file:///Volumes/Workplace/estore/tests_output/nightwatch-html-report/index.html:119:14885
Gr@file:///Volumes/Workplace/estore/tests_output/nightwatch-html-report/index.html:66:19519
Gh@file:///Volumes/Workplace/estore/tests_output/nightwatch-html-report/index.html:68:43962
Uh@file:///Volumes/Workplace/estore/tests_output/nightwatch-html-report/index.html:68:39726
Cb@file:///Volumes/Workplace/estore/tests_output/nightwatch-html-report/index.html:68:39654
W6@file:///Volumes/Workplace/estore/tests_output/nightwatch-html-report/index.html:68:39508
q9@file:///Volumes/Workplace/estore/tests_output/nightwatch-html-report/index.html:68:35876
zh@file:///Volumes/Workplace/estore/tests_output/nightwatch-html-report/index.html:68:34827
zh@[native code]
x@file:///Volumes/Workplace/estore/tests_output/nightwatch-html-report/index.html:53:1558
j@file:///Volumes/Workplace/estore/tests_output/nightwatch-html-report/index.html:53:1917
  ```

  

  <details>
  <summary>Nightwatch Report</summary>
  ```json
  ```
</details>

**Comment by AutomatedTester** [comment] 2023-03-29 15:35
Duplicate of #20

**Closed by AutomatedTester** 2023-03-29 15:35 UTC
