### ISSUE TITLE
[Bug]: Report failed to Render

### ISSUE THREAD

**Issue by Jaiganesh2613** [nightwatchjs/html-reporter#73] opened 2024-07-16 13:20 UTC
[Enter feedback here]
    
  ---

  **Error Details**
  ```javascript
  TypeError: Cannot read properties of undefined (reading 'environments')
    at yS (http://localhost:63342/Automation/tests_output/nightwatch-html-report/index.html?_ijt=dbmgllttc6p2cqck1l6eaatqn9:73:38180)
    at vS (http://localhost:63342/Automation/tests_output/nightwatch-html-report/index.html?_ijt=dbmgllttc6p2cqck1l6eaatqn9:73:38022)
    at wS (http://localhost:63342/Automation/tests_output/nightwatch-html-report/index.html?_ijt=dbmgllttc6p2cqck1l6eaatqn9:73:39687)
    at Ur (http://localhost:63342/Automation/tests_output/nightwatch-html-report/index.html?_ijt=dbmgllttc6p2cqck1l6eaatqn9:68:19518)
    at em (http://localhost:63342/Automation/tests_output/nightwatch-html-report/index.html?_ijt=dbmgllttc6p2cqck1l6eaatqn9:70:43960)
    at qh (http://localhost:63342/Automation/tests_output/nightwatch-html-report/index.html?_ijt=dbmgllttc6p2cqck1l6eaatqn9:70:39724)
    at Gw (http://localhost:63342/Automation/tests_output/nightwatch-html-report/index.html?_ijt=dbmgllttc6p2cqck1l6eaatqn9:70:39652)
    at q6 (http://localhost:63342/Automation/tests_output/nightwatch-html-report/index.html?_ijt=dbmgllttc6p2cqck1l6eaatqn9:70:39506)
    at q9 (http://localhost:63342/Automation/tests_output/nightwatch-html-report/index.html?_ijt=dbmgllttc6p2cqck1l6eaatqn9:70:35874)
    at Kh (http://localhost:63342/Automation/tests_output/nightwatch-html-report/index.html?_ijt=dbmgllttc6p2cqck1l6eaatqn9:70:34825)
  ```

  

  <details>
  <summary>Nightwatch Report</summary>
  ```json
  ```
</details>

**Comment by AutomatedTester** [comment] 2024-07-17 13:04
duplicate of #20

**Closed as not planned by AutomatedTester** 2024-07-17 13:04 UTC
