### ISSUE TITLE
[Bug]: Report failed to Render

### ISSUE THREAD

**Issue by UrsusAquaticus** [nightwatchjs/html-reporter#18] opened 2023-01-19 04:17 UTC
[Enter feedback here]
    
  ---

  **Error Details**
  ```javascript
  kA@file://///wsl$/Ubuntu-20.04/home/username/dev/tutorials/nightwatchcucumber/test-results/nightwatch-html-report/index.html:119:14506
TA@file://///wsl$/Ubuntu-20.04/home/username/dev/tutorials/nightwatchcucumber/test-results/nightwatch-html-report/index.html:119:14885
Gr@file://///wsl$/Ubuntu-20.04/home/username/dev/tutorials/nightwatchcucumber/test-results/nightwatch-html-report/index.html:66:19518
Gh@file://///wsl$/Ubuntu-20.04/home/username/dev/tutorials/nightwatchcucumber/test-results/nightwatch-html-report/index.html:68:43960
Uh@file://///wsl$/Ubuntu-20.04/home/username/dev/tutorials/nightwatchcucumber/test-results/nightwatch-html-report/index.html:68:39726
Cb@file://///wsl$/Ubuntu-20.04/home/username/dev/tutorials/nightwatchcucumber/test-results/nightwatch-html-report/index.html:68:39654
W6@file://///wsl$/Ubuntu-20.04/home/username/dev/tutorials/nightwatchcucumber/test-results/nightwatch-html-report/index.html:68:39506
q9@file://///wsl$/Ubuntu-20.04/home/username/dev/tutorials/nightwatchcucumber/test-results/nightwatch-html-report/index.html:68:35874
zh@file://///wsl$/Ubuntu-20.04/home/username/dev/tutorials/nightwatchcucumber/test-results/nightwatch-html-report/index.html:68:34825
x@file://///wsl$/Ubuntu-20.04/home/username/dev/tutorials/nightwatchcucumber/test-results/nightwatch-html-report/index.html:53:1558
j@file://///wsl$/Ubuntu-20.04/home/username/dev/tutorials/nightwatchcucumber/test-results/nightwatch-html-report/index.html:53:1916

  ```

  

  <details>
  <summary>Nightwatch Report</summary>
  ```json
  ```
</details>

**Comment by AutomatedTester** [comment] 2023-03-29 15:36
duplicate of #20

**Closed by AutomatedTester** 2023-03-29 15:36 UTC
