### ISSUE TITLE
[Bug]: Cucumber - Report failed to Render

### ISSUE THREAD

**Issue by sehajdeep1814** [nightwatchjs/html-reporter#32] opened 2023-06-30 09:27 UTC
[Enter feedback here]
    
  ---

  **Error Details**
  ```javascript
  TypeError: Cannot read properties of undefined (reading 'files')
    at EA (file:///c%3A/Users/nightwatch_tut/tests_output/nightwatch-html-report/index.html:121:14809)
    at TA (file:///c%3A/Users/nightwatch_tut/tests_output/nightwatch-html-report/index.html:121:15213)
    at Kr (file:///c%3A/Users/nightwatch_tut/tests_output/nightwatch-html-report/index.html:68:19518)
    at Qh (file:///c%3A/Users/nightwatch_tut/tests_output/nightwatch-html-report/index.html:70:43960)
    at Yh (file:///c%3A/Users/nightwatch_tut/tests_output/nightwatch-html-report/index.html:70:39724)
    at Wb (file:///c%3A/Users/nightwatch_tut/tests_output/nightwatch-html-report/index.html:70:39652)
    at ee (file:///c%3A/Users/nightwatch_tut/tests_output/nightwatch-html-report/index.html:70:39506)
    at cn (file:///c%3A/Users/nightwatch_tut/tests_output/nightwatch-html-report/index.html:70:35874)
    at Gh (file:///c%3A/Users/nightwatch_tut/tests_output/nightwatch-html-report/index.html:70:34825)
    at x (file:///c%3A/Users/nightwatch_tut/tests_output/nightwatch-html-report/index.html:55:1537)
  ```

  

  <details>
  <summary>Nightwatch Report</summary>
  ```json
  ```
</details>

**Comment by vaibhavsingh97** [comment] 2023-06-30 10:06
Hey @sehajdeep1814, would you mind updating the issue template and providing possible steps to reproduce the problem? Thank you!

**Comment by sehajdeep1814** [comment] 2023-06-30 10:56
Hey @vaibhavsingh97, so this issue arises when I'm trying to run step-definitions using cucumber test runner and nightwatch.js. The tests are passed successfully but I'm not able to open the HTML report as it gives the error mentioned above

**Comment by vaibhavsingh97** [comment] 2023-07-06 17:01
Hi @sehajdeep1814, at the moment HTML Reporter is not compatible with cucumber.

**Comment by cvacalares** [comment] 2023-08-08 06:35
Hi! Any estimate when this will be made compatible?

**Comment by AutomatedTester** [comment] 2024-02-16 10:53
duplicate of #20

**Closed by AutomatedTester** 2024-02-16 10:53 UTC
