### ISSUE TITLE
[Bug]: Report failed to Render

### ISSUE THREAD

**Issue by KevinPaizRamos** [nightwatchjs/html-reporter#71] opened 2024-06-10 19:04 UTC
[Enter feedback here]
    
  ---

  **Error Details**
  ```javascript
  TypeError: Cannot read properties of undefined (reading 'files')
    at CA (file:///C:/Users/KevinPaizRamos/webapp/tests_output/nightwatch-html-report/index.html:121:14809)
    at $A (file:///C:/Users/KevinPaizRamos/webapp/tests_output/nightwatch-html-report/index.html:121:15213)
    at Ur (file:///C:/Users/KevinPaizRamos/webapp/tests_output/nightwatch-html-report/index.html:68:19518)
    at em (file:///C:/Users/KevinPaizRamos/webapp/tests_output/nightwatch-html-report/index.html:70:43960)
    at qh (file:///C:/Users/KevinPaizRamos/webapp/tests_output/nightwatch-html-report/index.html:70:39724)
    at Gw (file:///C:/Users/KevinPaizRamos/webapp/tests_output/nightwatch-html-report/index.html:70:39652)
    at q6 (file:///C:/Users/KevinPaizRamos/webapp/tests_output/nightwatch-html-report/index.html:70:39506)
    at q9 (file:///C:/Users/KevinPaizRamos/webapp/tests_output/nightwatch-html-report/index.html:70:35874)
    at Kh (file:///C:/Users/KevinPaizRamos/webapp/tests_output/nightwatch-html-report/index.html:70:34825)
    at b (file:///C:/Users/KevinPaizRamos/webapp/tests_output/nightwatch-html-report/index.html:55:1537)
  ```

  

  <details>
  <summary>Nightwatch Report</summary>
  ```json
  ```
</details>

**Comment by AutomatedTester** [comment] 2024-06-17 10:34
Duplicate of #20

**Closed by AutomatedTester** 2024-06-17 10:34 UTC
